### ISSUE TITLE
Feature: allow specifying default configuration options

### ISSUE THREAD

**Issue by mpareja** [mpareja/paprika#2]
You'll often want to use the same configuration settings across similar tasks. We should support specifying those common values once and only specifying the specifics for each task.

Here is a suggestion from @prabirshrestha:

```
var msbuild = require('paprika').msbuild;
msbuild.config({ version: 'net35', processor: 'x86', properties: { Configuration: 'Release' } });

task('build', function () {
    msbuild({
        file: '../MySolution.sln'
      , targets: ['Clean', 'Build']
      , show_stdout: false
    });
};
```

**Comment by prabirshrestha** [comment]
could you update the npm package. the latest on in npm doesn't seem to include msbuild.setDefaults({}) method.

**Comment by mpareja** [comment]
Done.

**Comment by prabirshrestha** [comment]
papriaka is now breaking.

``` js
$ jake
Invalid .NET framework version 'undefined' or processor 'x86'
jake aborted.
```

event without using `setDefaults`

``` js
task('build', function () {
    msbuild({
        file: path.join(rootpath, 'Source/AzureToolkit.sln'),
        targets: ['Build'],
        processor: 'x86',
        version: 'net40'
    });
});
```

undefined

**Comment by mpareja** [comment]
Sorry about that, where I am right now, I didn't have a quick environment for running an end-to-end test.  I missed the version parameter when adding support for specifying default configurations.

I've pushed my changes and updated the npm package.  Have a go and let me know.

**Comment by prabirshrestha** [comment]
works great now.

thanks for the fast responses.
